### ISSUE TITLE
Add Continuous Integration with Circle CI

### ISSUE THREAD

**Issue by brendanebers** [brendanebers/wheresbrendan#1]
A couple possibilities:
https://travis-ci.org/
https://circleci.com/

Once complete, Heroku settings should be updated to only pull once CI completes.

**Comment by organicveggie** [comment]
Unfortunately, I can't add your repos to Travis CI; only you can do that. However, we could move to a GitHub [Organization](https://github.com/blog/674-introducing-organizations) instead. They're free for open source projects.

Otherwise, you'll want to:

1. Go to https://travis-ci.org/
1. Sign in with your GitHub account
1. Go to https://travis-ci.org/profile/brendanebers
1. Flick the switch for the brendanebers/wheresbrendan repo

**Comment by brendanebers** [comment]
Fwitch slipped, need to add a .travis.yml file to get everything going.

**Comment by brendanebers** [comment]
Change 70e38220f288a3bc717125cb65cb41cde1e85a47 finally did away with the circle ci "Build Failed" emails I was getting. This is closed!
